spring:
  application:
    name: hrbank
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

hrbank:
  local:
    path: localFile

backup:
  schedule:
    cron: "0 0 * * * *"  # 초 분 시 일 월 요일
