spring:
  application:
    name: hrbank
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank_user
    password: hrbank1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace